import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import { CryptoData } from '../type'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'

const Home:NextPage<{data: CryptoData[]}> = ({data}) => {
  console.log(data)
  return (
    <div className={styles.container}>
      <Head>
        <title>Crypto-dash</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to crypto-dash
        </h1>
        <div className={styles.cardContainer}>
          {data.map((crypto: CryptoData) => (
          <div className={styles.card} key={crypto.id}>
              <Image
                src={crypto.image}
                alt={crypto.name}
                width={100}
                height={100}
              />
              <h2>{crypto.name}</h2> 
              <p>PRICE : {crypto.current_price.toLocaleString("en-IN", {style:'currency', currency: 'INR'})}</p> 
          </div>
        ))}
        </div>
        
      </main>
    </div>
  )
}

export default Home

export const getServerSideProps: GetServerSideProps = async () => {
  const res = await fetch('https://api.coingecko.com/api/v3/coins/markets?vs_currency=inr')
  const data: CryptoData[] = await res.json()

  return {
    props: {
      data
    }
  }
}
